import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useRef } from "react";
import Typed from "typed.js";

export default function Home() {
  useEffect(() => {
    const type1 = new Typed(".auto-type", {
      strings: ["Sujan Ghimire"],
      startDelay: 300,
      typeSpeed: 100,
      // backDelay: 300,
      showCursor: false,
      loop: false,
      onComplete: () => {
        const type2 = new Typed(".auto-type2", {
          strings: ["Web Development"],
          startDelay: 300,
          typeSpeed: 100,
          // backDelay: 300,
          showCursor: false,

          loop: false,
        });
      },
    });
  }, []);

  return (
    <>
      <Head>
        <title>Sujan Ghimire</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.wrapper}>
          <div className={styles.wrapper__left}>
            <div className={styles.intro}>
              <h1>Hi There,</h1>
              <h1>
                I'm <span className="auto-type"></span>
              </h1>
            </div>
            <div className={styles.desc}>
              <p>
                I Am Into <span className="auto-type2"></span>
              </p>
            </div>
            <div className={styles.about__btn}>
              <button>
                About <span>me</span>
              </button>
            </div>
            <div className={styles.social__links}>
              <div>
                <Image
                  src="/images/social-icons/facebook.png"
                  alt="facebook"
                  width={40}
                  height={40}
                />
              </div>
              <div>
                <Image
                  src="/images/social-icons/linkedin.png"
                  alt="linkedin"
                  width={40}
                  height={40}
                />
              </div>
              <div>
                <Image
                  src="/images/social-icons/twitter.png"
                  alt="twitter"
                  width={40}
                  height={40}
                />
              </div>
              <div>
                <Image
                  src="/images/social-icons/github.png"
                  alt="github"
                  width={40}
                  height={40}
                />
              </div>
              <div>
                <Image
                  src="/images/social-icons/instagram.png"
                  alt="instagram"
                  width={40}
                  height={40}
                />
              </div>
            </div>
          </div>
          <div className={styles.wrapper__right}>
            <Image
              style={{
                borderRadius: "50%",
                objectFit: "cover",
                objectPosition: "55%",
              }}
              src="/images/boss-baby.jfif"
              alt="boss-baby"
              width={500}
              height={500}
            />
          </div>
        </div>
      </div>
    </>
  );
}
